name: Deploy to server

on:
  push:
    branches: [ main, develop ]

env:
  NODE_ENV: production
  PORT: 22
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy with PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/42ManagerBack
          git pull
          npm run deploy
